version: 2.1

orbs:
  node: circleci/node@1.1.2

jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - node/install-yarn
      - node/with-cache:
          steps:
            - run: yarn install --frozen-lockfile
            - run: yarn validate
            - run: yarn semantic-release
